language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
  - dotnet build src/Silo.sln
  - dotnet test src/Silo.sln
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1